comment: 'Parameters for D_PDC on Cifar100'
learning_rate: 0.1

dataset:
  root: /tmp/
  batch_size: 128
  db: cifar100

model:
  fn: models/D_PDC.py
  name: D_PDC_wrapper
  args:
    train: True
    use_activ: False
    use_alpha: True
    n_lconvs: 1
    use_lactiv: False
    norm_local: 0
    num_blocks: [2, 2, 2, 1]
    kern_loc: 3
    kern_loc_so: 3

    out_activ: False
    n_channels: [64, 128, 192, 256]
    planes_ho:  [64, 64, 128, 128]

    use_only_first_conv: False

    use_active: False
    use_so_activ: False
    use_pr_activ: False    

    div_std: 0
    n_xconvs: 0
    norm_x: -1
    norm_layer: [a, a, a, 0]
    norm_pr: 2
    use_theta: True
    skip_con_dense: True 
    use_pr_conv: True
    append_bef_norm: True
    use_sep_short: True
    num_classes: 100


training_info:
  total_epochs: 120
  display_interval: 200
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  smoothing: 0.4
  multi_step: True
  exponential_step: False
