comment: 'Parameters for R_PDC on STL10'
learning_rate: 0.1

dataset:
  root: /tmp/
  batch_size: 128
  db: STL10

model:
  fn: models/R_PDC.py
  name: R_PDC_wrapper
  args:
    train: True
    use_activ: False
    use_alpha: True
    n_lconvs: 1
    use_lactiv: False
    num_blocks: [2, 2, 2, 1]
    kern_loc: 3
    kern_loc_so: 3
    norm_x: -1
    out_activ: False
    n_channels: [64, 128, 256, 256] 
    planes_ho:  [64, 64, 128, 128]
    norm_layer: [a, a, a, 0] 
    use_only_first_conv: False
    pool_adapt: True  #for STL10
    norm_local: 0
  
training_info:
  total_epochs: 120
  display_interval: 200
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  smoothing: 0.1
  multi_step: True
  exponential_step: False  
