comment: 'Parameters for R_PolyNets on Speech Commands dataset'
learning_rate: 0.1

dataset:
  batch_size: 128
  db: speech
  train_dataset: /content/drive/MyDrive/epfl_normalization_polynomials/datasets/speech_commands/data2/speech/train # please change the rootdir into the directory containing Speech Commands train dataset
  valid_dataset: /content/drive/MyDrive/epfl_normalization_polynomials/datasets/speech_commands/data2/speech/valid # please change the rootdir into the directory containing Speech Commands valid dataset

model:
  fn: models/R_PolyNets.py
  name: R_PolyNets_wrapper
  args:
    train: True
    use_activ: False 
    use_alpha: True
    n_lconvs: 1
    norm_local: 0
    num_blocks: [2, 2, 2, 2]
    norm_x: -1 
    n_xconvs: 0
    norm_layer: [a, a, a, 0] 
    num_classes: 37
    ch_in: 1

training_info:
  total_epochs: 120
  display_interval: 200
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  smoothing: 0.1
  multi_step: True
  exponential_step: False


