comment: 'Parameters for R_PolyNets on STL10'
learning_rate: 0.1

dataset:
  root: /tmp/
  batch_size: 128
  db: STL10 #change from cifar

model:
  fn: models/R_PolyNets.py
  name: R_PolyNets_wrapper
  args:
    train: True
    use_activ: False 
    use_alpha: True
    n_lconvs: 1
    norm_local: 0 
    num_blocks: [2, 2, 2, 2]
    norm_x: -1 
    n_xconvs: 0
    norm_layer: [a, a, a, 0] 
    pool_adapt: True  

training_info:
  total_epochs: 120
  display_interval: 200
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  smoothing: 0.1
  multi_step: True
  exponential_step: False
