comment: 'Parameters for R_PolyNets on Oxford Flowers'
learning_rate: 0.1 # change from 0.1

dataset:
  root: /content/drive/My Drive/epfl_normalization_polynomials/oxford-102-flower-pytorch/flower_data/flower_data # please change the rootdir into the directory containing Oxford Flowers dataset
  batch_size: 64
  db: oxford_flower #change from cifar
  trainf: train
  testf: valid

model:
  fn: models/R_PolyNets.py
  name: R_PolyNets_wrapper
  args:
    train: True
    use_alpha: False 
    n_lconvs: 1 
    norm_local: 0 
    num_blocks: [2, 2, 2, 2] 
    norm_x: -1 
    n_xconvs: 0
    norm_layer: [a, a, a, 0] 
    pool_adapt: True  
    num_classes: 102 

training_info:
  total_epochs: 120
  display_interval: 200
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  smoothing: 0.4
  multi_step: True
  exponential_step: False
