comment: 'Parameters for R_PolyNets on Cifar100'
learning_rate: 0.1

dataset:
  root: /vol/deform/grigoris/data/2019_resnet/data/
  batch_size: 128
  db: cifar100

model:
  fn: models/R_PolyNets.py
  name: R_PolyNets_wrapper
  args:
    train: True
    use_activ: False
    num_classes: 100
    use_alpha: False
    n_lconvs: 1
    norm_local: 0 
    norm_layer: [a, a, a, 0] 
    num_blocks: [2, 2, 2, 2] 

training_info:
  total_epochs: 120
  display_interval: 200
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  smoothing: 0.4
  multi_step: True
  exponential_step: False
