comment: 'Parameters for R_PolyNets on Cifar10'
learning_rate: 0.1

dataset:
  root: /tmp/
  batch_size: 128
  db: cifar #change from cifar

model:
  fn: models/R_PolyNets.py
  name: R_PolyNets_wrapper
  args:
    train: True
    use_alpha: True 
    n_lconvs: 1
    norm_local: 0 
    num_blocks: [2,2,2,2] # change from [2,2,2,2] 
    norm_x: -1 
    n_xconvs: 0
    norm_layer: [a, a, a, 0] # add change from 0


training_info:
  total_epochs: 120
  display_interval: 200
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  smoothing: 0.1
  multi_step: True
  exponential_step: False
